### ISSUE TITLE
Mapping PADV: Kommentar

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#16]
Das Mapping des PADV Kommentars ist folgendermassen definiert:
* **CDA:** section.entry.observation.text.reference -> Bsp: value="#padv.1" 
   * (siehe [Art-Decor](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.44&effectiveDate=2016-06-25T00:00:00&language=en-US))
* **FHIR:** Observation.note

Der Wert, der bei FHIR Observation.note erwartet wird ist folgender:
`<td ID="padv.1.note">Abgesetzt aufgrund UAW trockener Husten</td>`
(Bsp. 2-2-PharmaceuticalAdvice)

Das Mapping von CDA->FHIR und FHIR->CDA ist noch offen. Wie kann das richtige Element aus dem Text evaluiert werden?

**Comment by oliveregger** [comment]
value reference muss auf padv.1.note gesetzt werden: 	<reference value="#padv.1.note" /> um Abgesetzt aufgrund UAW trockener Husten zu erhalten, muss das CDA-CH Beispiel noch angepasst werden @ziegm ?

**Comment by oliveregger** [comment]
wir fügen bei der note die narrativeLink extension hinzu, beim Mapping zurück gehen wir aber davon wieder aus, dass diese narrativLink extension vorhanden ist und mit dem note.text übereinstimmt (warnung: // Note/Warning: we assume that there is a narrativeLink extension which refers to the text which should be the same as in note.text)

**Comment by ziegm** [comment]
> value reference muss auf padv.1.note gesetzt werden: um Abgesetzt aufgrund UAW trockener Husten zu erhalten, muss das CDA-CH Beispiel noch angepasst werden @ziegm ?

CDA-CH Beispiel angepasst: https://github.com/hl7ch/hl7ch-cda/commit/26fbf78f927fae5eaee7a6727cd146be830705ae

**Comment by ziegm** [comment]
@oliveregger 
Passt das noch mit der narrativeLink Extension?

Transformation von CDA zu FHIR ergibt folgenden Fehler:

```xml
<OperationOutcome xmlns="http://hl7.org/fhir">
  <issue>
    <severity value="error"></severity>
    <code value="processing"></code>
    <diagnostics value="Failed to call access method: org.hl7.fhir.exceptions.FHIRException: Unknown input variable text in http://fhir.ch/ig/cda-fhir-maps/StructureMap/CdaChEmedToBundle rule level3 (vars = source variables [section: (http://hl7.org/fhir/cda/StructureDefinition/Section), src: (http://hl7.org/fhir/cda/StructureDefinition/Observation), patient: (Patient)], target variables [observation: (Observation), note: (Annotation)], shared variables [])"></diagnostics>
  </issue>
</OperationOutcome>
```
