### ISSUE TITLE
adjustment of the mapping of the dataenterer necessary due to change in the ch core

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#18]
Change in CH Core:
[EPRDataEnterer: valueReference only to Practitioner (not Person) #85](https://github.com/hl7ch/ch-core/issues/85)

CDA-FHIR-Maps -> Change Reference from Person to Practitioner
* CDA to FHIR: input\maps\CdaChToBundle.map
   * Line 138: `group ChExtEprDataEnterer`
   * Line 173: call of this rule
* FHIR to CDA: input\maps\BundleToCdaCh.map
   * Line 168: `rule dataEnterer`

**Comment by oliveregger** [comment]
fixed, but see also issue https://github.com/hl7ch/ch-core/issues/93 which should be considered

**Comment by ziegm** [comment]
Mapping FHIR to CDA (CdaContainingOriginalRepresentationAsPdfA.xml) is not correct:
```xml
  <dataEnterer>
    <templateId root="2.16.756.5.30.1.1.10.2.7"/>
    <time value="20171003131500+0100"/>
  </dataEnterer>
```

**Comment by ziegm** [comment]
Mapping CDA to FHIR  (CdaContainingOriginalRepresentationAsPdfA.xml) needs to be updated to PractitionerRole instead of Practitioner.

[CH Core Data Enterer](http://fhir.ch/ig/ch-core/StructureDefinition-ch-ext-epr-dataenterer.html) refers only to PractitionerRole.
