### ISSUE TITLE
CDA -> FHIR: quantity mapping isn't complete

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#19]
Transformation from CDA to FHIR

actual mapping:
`<doseQuantity value="40" unit="mg"/>`

```
"doseAndRate": [{
       "doseQuantity": {
                "value": 40,
                 "code": "mg"
          }
      }
]
```

Validation error: qty-3: If a code for the unit is present, the system SHALL also be present [code.empty() or system.exists()]

target mapping:
```
"doseQuantity": {
      "value": 40,
      "unit": "mg",
      "system": "http://unitsofmeasure.org",
      "code": "mg"
},
```

**Comment by oliveregger** [comment]
@ziegm can you add a link to the source file this is happening?

**Comment by ziegm** [comment]
https://github.com/hl7ch/cda-fhir-maps/blob/master/input/cda-ch-emed/pmlc2.xml

**Comment by ziegm** [comment]
reviewed and tested
