### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#2]
Encoding problems have been noticed in the following cases:
CDA document:
`<city>Z&#xFC;rich</city>`
`<family>Wegm&#xFC;ller</family>`
`<th>Pr&#xE4;partename</th>`

FHIR document:
`<family value="Wegm&#xFC;ller"/>`
`<city value="Z&#xFC;rich"/>`

**Comment by ziegm** [comment]
Encoding problem now occurs only in one direction:
Transformation of any document from **CDA to FHIR**

Examples in any transformed FHIR document:

Präparatename: works (Composition.section.text)
Packungsgrösse: works (Composition.section.text)
Durchführung: works (Composition.section.text)
gewünschten: works (Composition.section.text)

`Gewünschte -> Gew&#xFC;nschte`: does not work (Composition.section.title)
`Zürich -> Z&#xFC;rich`: does not work (Patient.address.city)
`Wegmüller -> Wegm&#xFC;ller`; does not work (Patient.name.family)
`für -> f&#xFC;r`: does not work (Organization.name, Practitioner.name.suffix)
`Medikamentöser -> Medikament&#xF6;ser`: does not work (Composition.section.title)
`Röntgenstr. -> R&#xF6;ntgenstr.`: does not work (Organization.address.line)

**Comment by oliveregger** [comment]
fixed with https://github.com/ahdis/matchbox/releases/tag/0.8.16

        <section>
          <title value="Gewünschte Untersuchung"/>
          <text>
