### ISSUE TITLE
FHIR to CDA conversion problems Medication Treatment Plan

### ISSUE THREAD

**Issue by oliveregger** [ahdis/cda-fhir-maps#21]
Validation is not converting correctly:
- patientRole.id missing
- check maybe section order
- missing id on the representedCustodianOrganization
- missing references for narrative text
- timing events

https://ehealthsuisse.ihe-europe.net/EVSClient//detailedResult.seam?type=FHIR&oid=1.3.6.1.4.1.12559.11.25.1.13.47855

https://ehealthsuisse.ihe-europe.net/EVSClient//detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.13.47845

**Comment by qligier** [comment]
Every value that goes into a CDA ID attribute should be checked. For this file, 
```json
{
 "resource":{
   "resourceType":"Binary",
   "id":"1",
   ...
  }
}
```
gives the invalid 
```xml
<observationMedia ID="1" ... />
```
CDA IDs must follow [the xs:NCName restrictions](https://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName):
``` 
    NCName ::= (Letter | '_') (NCNameChar)*
NCNameChar ::= Letter | Digit | '.' | '-' | '_' | CombiningChar | Extender
```

**Comment by oliveregger** [comment]
patientRole.id missing -> Patient.identifier system is http based, this is not working with CDA, we need an oid system identifier.

**Comment by oliveregger** [comment]
missing id on the representedCustodianOrganization -> Organization.identifier system is http based, this is not working with CDA, we need an oid system identifier.

**Comment by oliveregger** [comment]
timingevents occured multiple times, because sequence numbers were not provided for dosage. 

https://github.com/ehealthsuisse/ch-emed/issues/58

**Comment by oliveregger** [comment]
CDA Validation: https://ehealthsuisse.ihe-europe.net/EVSClient//detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.13.48407

CH-EMED Validation https://ehealthsuisse.ihe-europe.net/EVSClient//detailedResult.seam?type=FHIR&oid=1.3.6.1.4.1.12559.11.25.1.13.48408 (error due to truncated pdf)
