### ISSUE TITLE
FHIR -> CDA: free text medication (no gtin), cda needs the element code with NA

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#22]
CDA:
manufacturedMaterial.code 1..1
see [spec](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.34&effectiveDate=2019-12-11T11:31:52&language=en-US):   
_The element SHALL be present and describes the code of the medication (GTIN). If it as magistral preparation/compound medicin nullFlavor SHALL be NA_

FHIR [Source file](https://github.com/hl7ch/cda-fhir-maps/blob/master/input/ch-emed/card.json)
only `Medication.code.text` is required

**TBD for Transformation**
Generating this part for CDA:
`<code code="7680460380107" codeSystem="2.51.1.1" codeSystemName="Global Trade Item Number" displayName="NA"/>`

**Comment by oliveregger** [comment]
added nullFlavor, @ziegm not clear what I should do about "TBD for Transformation"

**Comment by ziegm** [comment]
@oliveregger Wenn im FHIR nur das Element text vorhanden ist (kein coding), dann soll im CDA der code mit nullFlavor generiert werden bei der Transformation.

**Comment by ziegm** [comment]
checked
