### ISSUE TITLE
FHIR -> CDA: element substanceAdministration.text.reference is not generated

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#23]
source [File FHIR](https://github.com/hl7ch/cda-fhir-maps/blob/master/input/ch-emed/card.json)
Composition.section:Medikamentenliste

no `substanceAdministration.text.reference` is generated for cda

**Comment by oliveregger** [comment]
see also https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.30&language=en-US

**Comment by oliveregger** [comment]
Quentin Ligier categorized three different types of narrative text/structured entry relations
Only category 2 is problematic; a change proposal has to be submitted to PCC. In the meantime, the concerned data will be moved into the structured (instead of narrative) part in order to ease/enable the conversion into FHIR format

**Comment by oliveregger** [comment]
Category 1: no associated data

These mandatory ones bind the whole entry to the narrative text. The plan for them would be to target a simple "see pdf" text.

substanceAdministration/text/reference (MTP/PRE item)
supply/text/reference (DIS item)
observation/text/reference (PADV item)

**Comment by oliveregger** [comment]
Category 2: data in the narrative text only
These references are the problematic ones, where the data is not present in the structured data but only in the narrative text. That's the ones targeted by the two proposals.

observation/text/reference (Treatment Reason Entry Content Module)
act/text/reference (Patient Medication Instructions, Fulfillment Instructions, Annotation Comments, Pharmaceutical Advice Concern Entry Content Module)
substanceAdministration/precondition/criterion/text/reference (MTP/PRE item)
substanceAdministration/text/reference (Dosage Instructions Non Structured Entry Content Module, Dosage Intake Mode Entry Content Module)

**Comment by oliveregger** [comment]
Category 3: structured data and narrative text
These optional references bind a structured data to a human representation in the narrative text. If the PDF is required, we could mark them as neither useful nor expected by data consumers (as they would be capable of generating again the human representation from the structured data).

substanceAdministration/effectiveTime/offset/(low|center|width|high)/translation/originalText/reference (MTP item, Dosage Instructions Dosage Change)
substanceAdministration/routeCode (mutliple refs, Dosage Instructions Start/Stop, Frequency, Dose)
substanceAdministration/approachSiteCode (mutliple refs, Dosage Instructions Start/Stop, Frequency, Dose)
substanceAdministration/doseQuantity (mutliple refs, Dosage Instructions Start/Stop, Frequency, Dose, Dosage Instructions Dosage Change)
substanceAdministration/rateQuantity (mutliple refs, Dosage Instructions Start/Stop, Frequency, Dose, Dosage Instructions Dosage Change)
substanceAdministration/code (multiple refs, MTP/PRE Reference Entry Content Module)
act/code (multiple refs, Patient Medication Instructions, Fulfillment Instructions, Substitution Permission Content Module, IHE Substitution Act Content Module, Pharmaceutical Advice Concern Entry Content Module)
functionCode (multiple refs, 2.16.756.5.30.1.1.10.9.54)
addr (multiple refs, 2.16.756.5.30.1.1.10.9.54, 2.16.756.5.30.1.1.10.9.27)
name (multiple refs, 2.16.756.5.30.1.1.10.9.27, 2.16.756.5.30.1.1.10.9.34)
manufacturerModelName/reference (2.16.756.5.30.1.1.10.9.21)
softwareName/reference (2.16.756.5.30.1.1.10.9.21)
manufacturedMaterial/code (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/name (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:formCode (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:asContent/pharm:containerPackagedMedicine/pharm:code (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:asContent/pharm:containerPackagedMedicine/pharm:name (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:asContent/pharm:containerPackagedMedicine/pharm:formCode (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:asContent/pharm:containerPackagedMedicine/pharm:capacityQuantity/translation/reference (Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:ingredient/pharm:quantity/numerator/translation/reference (Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:ingredient/pharm:quantity/denominator/translation/reference (Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:ingredient/pharm:ingredient/pharm:code (multiple refs, Manufactured Material Entry Content Module)
manufacturedMaterial/pharm:ingredient/pharm:ingredient/pharm:name (multiple refs, Manufactured Material Entry Content Module)
supply/effectiveTime/width/translation/originalText/reference (Renewal Period Content Module)
supply/code (multiple refs, DIS item)
supply/quantity/translation/originalText/reference (DIS item)
observation/code (multiple refs, PADV item, PADV Reference Entry Content Module)
act/effectiveTime (multiple refs, Pharmaceutical Advice Concern Entry Content Module)

**Comment by oliveregger** [comment]
@ziegm kannst Du das mit HCI aufnehmen dass sie dort die text section nicht generieren?

**Comment by ziegm** [comment]
@oliveregger Müsste man im CH EMED dann nicht die Elemente text auf 0..0 setzen in Composition.section:card.text und Composition.section:prescription.text? Also bei den Dokumenten, die eine Original Representation beinhalten. Ansonsten können valide FHIR Dokumente nicht korrekt gemappt werden oder?

**Comment by oliveregger** [comment]
ausser meiner Sicht nicht notwendig, wenn sie einen eigene Repräsentation generieren wird das ensptrechend auf CDA gemapped, oder hattest Du ein Problem damit?
