### ISSUE TITLE
pharm:capacityQuantity mapping nullFlavor is missing

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#26]
FHIR -> CDA:
If there is no Medication.amount there should be a nullFlavor for pharm:capacityQuantity

`<pharm:capacityQuantity nullFlavor="NP"/>`

see [Spec](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.34&effectiveDate=2019-12-11T11:31:52&language=en-US)

**Comment by ziegm** [comment]
[Validation result](https://ehealthsuisse.ihe-europe.net/EVSClient//detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.13.48447)

should the value be required or should that be changed in the spec?

**Comment by oliveregger** [comment]
1. Spec sagt akutell 0..1
2. Es ist noch ein Open Issue in ArtDecor offen zu dem Thema 
3. https://art-decor.org/art-decor/decor-issues--ch-pharm-?id=2.16.756.5.30.1.127.77.4.6.35&language=en-US ch-pharm-issue-34 package size defined as optional or required?

**Comment by qligier** [comment]
The package size is optional, and if present, it shall have a value and unit (i.e. the null flavor is disallowed). The template has been updated.

**Comment by oliveregger** [comment]
thanks @qligier!
