### ISSUE TITLE
FHIR -> CDA: missing author.assignedAuthor

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#34]
CDA requires the **author.assignedAuthor**, see [spec](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.9.23&effectiveDate=2019-09-12T13:48:28&language=en-US).

Required elements for assignedAuthor are:
- hl7:id (The specification of GS1 GLN is REQUIRED. If it is not (yet) known, this MUST be declared using nullFlavor.)
- Elements to choose from:
   - hl7:assignedPerson
   - hl7:assignedAuthoringDevice

In the FHIR source these elements aren't required.

Note:
If there is a reference to a PractitionerRole from Composition.author the mapping doesn't work.

Examples:
- [PADV-CANCEL.json](https://github.com/hl7ch/cda-fhir-maps/blob/additionalExamples/input/ch-emed/PADV-CANCEL.json)
   - https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.1352548
- [PADV-CHANGE.json](https://github.com/hl7ch/cda-fhir-maps/blob/additionalExamples/input/ch-emed/PADV-CHANGE.json)
   - https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.1352549

**Comment by oliveregger** [comment]
won't fix, see https://github.com/ehealthsuisse/ch-emed/issues/80
