### ISSUE TITLE
FHIR -> CDA: PADV - missing observation.entryRelationship

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#35]
The element **hl7:observation.hl7:entryRelationship** is not mapped with these examples ([spec](https://art-decor.org/art-decor/decor-templates--cdachemed-?section=templates&id=2.16.756.5.30.1.1.10.4.44&effectiveDate=2016-06-25T00:00:00&language=en-US)):

- [PADV-CANCEL.json](https://github.com/hl7ch/cda-fhir-maps/blob/additionalExamples/input/ch-emed/PADV-CANCEL.json)
   - https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.1352548
- [PADV-CHANGE.json](https://github.com/hl7ch/cda-fhir-maps/blob/additionalExamples/input/ch-emed/PADV-CHANGE.json)
   - https://ehealthsuisse.ihe-europe.net/EVSClient/detailedResult.seam?type=CDA&oid=1.3.6.1.4.1.12559.11.25.1.1352549

Error:
(PharmaceuticalAdviceItemEntryContentModule): choice (hl7:entryRelationship[@typeCode='REFR' and hl7:substanceAdministration[hl7:templateId[@root='2.16.756.5.30.1.1.10.4.45']]] or hl7:entryRelationship[@typeCode='REFR' and hl7:supply[hl7:templateId[@root='2.16.756.5.30.1.1.10.4.46']]] or hl7:entryRelationship[@typeCode='REFR' and hl7:substanceAdministration[hl7:templateId[@root='2.16.756.5.30.1.1.10.4.47']]]) does not contain enough elements [min 1x]

**Comment by oliveregger** [comment]
Both of these examples do not add a reference to the original medicationstatement, therefore the information cannot be mapped to CDA. See example in spec how the reference is done: 

http://fhir.ch/ig/ch-emed/Bundle-PharmaceuticalAdvice-ChangeDosage.xml.html

              
                <extension url="http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-medicationstatement-changed">
                    <valueReference>
                        <reference value="MedicationStatement/MedStatTriatec-ChangeDosage"/>
                    </valueReference>
                </extension>
