### ISSUE TITLE
Missing mapping for different authors (on different levels)

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#48]
FHIR: [source file](http://fhir.ch/ig/ch-emed/Bundle-MedicationCard-DifferentAuthors.json.html)
* Composition.author
   * Practitioner/AuthorDocument: mapping done
   * Organization/AuthorDocumentOrganization: mapping done
* Composition.section.author
   * Practitioner/AuthorSection
   * Organization/AuthorSectionOrganization
* MedicationStatement.extension:ch-emed-ext-documentauthor
   * Practitioner/AuthorOriginalDocument
   * Organization/AuthorOriginalDocumentOrganization
* MedicationStatement.informationSource
   * .extension:ch-emed-ext-representedorganization: Organization/AuthorMedicalDecisionOrganization
   * Practitioner/AuthorMedicalDecision

for mapping details see [here](https://docs.google.com/spreadsheets/d/1IBUy4QDELjJ2YeepeC1wv0elxP99QKOUiKgzmg7fBhQ/edit#gid=0)

**Comment by oliveregger** [comment]
- mapped always from PractitionerRole (not Practitioner or Organization separate)
- open ch-emed ballot issues see https://github.com/hl7ch/ch-emed/issues/114 and https://github.com/hl7ch/ch-emed/issues/113
- also added for dis, pre, padv not only mtp
