### ISSUE TITLE
empty narrative

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-fhir-maps#55]
if there is no content in the narrative, could we add a default text (e.g. no content, -) there, that we have a valid document?

**Comment by oliveregger** [comment]
where does this happen? there should be not no content in the narrative ..

**Comment by ziegm** [comment]
the problem was solved already during the projectathon with quentin, there was a missing element in the cda document.

**Comment by qligier** [comment]
If I remember correctly, there was no missing element, the narrative content looked like `<text><content id="narrative" /></text>`. It passes CDA validation, but the FHIR validator complained about the transformed content (because the HTML contained only elements, no text?).

**Comment by ziegm** [comment]
@qligier thanks for the comment. I thought Pedro (monitor of that Gazelle test) told me then you added text? Is the CDA validation correct? Does it make sense to have an empty narrative?

**Comment by qligier** [comment]
The CDA validator only checks for the existence of referenced IDs, so we may encounter this issue again. But I'd prefer to fix the current state of narrative texts before fixing such small details :)
